version: "3"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'govtech'
      MYSQL_USER: 'govtech'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume:
